// let defaultConfig = require('tailwindcss/defaultConfig')

module.exports = {
  prefix: '',
  important: false,
  purge: false,
  separator: ':',
  theme: {
    colors: {
      theme1: {
        mainPrimary: '#282c34',
        mainSecondary: '#22262e',
        miscPrimary: '#a4abb0',
        miscSecondary: '#878b92',
        editorBg: '#33373d',
        textContrast: '#f3f3f3',
        lightyContrast: '#fff',
        okColor: '#89ca78',
        attentionColor: '#ff9b46',
        warningColor: '#ef596f',
        paramColor: '#61afef',
        categoryColor: '#d55fde',
        listColor: '#d19a66',
        activeMainNavLinkBg: '#5c6370',
        borderColor: '#282c34',
        dropdownColor: '#22262e',
        toggleColor: '#89ca78',
        toggleInactiveColor: '#5c6370',
        menuSearchColor: '#ff9b46',
        responseColor: '#706F6B',
        green: '#89ca78',
        orange: '#ff9b46',
        red: '#ef596f',
        textHighlightColor: '#61afef',
        toolbarIconColor: '#89ca78',
        textTemplateLabel: '#a4abb0',
        textTemplateComment: '#7f8285',
        textTemplateBlue: '#61afef',
        textTemplateGreen: '#89ca78',
        textTemplateBlueOpacity: '#5e91bd',
        textTemplateGreenOpacity: '#4fa065',
      },
      theme2: {
        mainPrimary: '#f0f8ff',
        mainSecondary: '#cbe8f5',
        miscPrimary: '#708f9d',
        miscSecondary: '#6e7f86',
        editorBg: '#c1e4f2',
        textContrast: '#255666',
        lightyContrast: '#fff',
        okColor: '#a7ccde',
        attentionColor: '#a7ccde',
        warningColor: '#a7ccde',
        paramColor: '#396273',
        categoryColor: '#396273',
        listColor: '#e7833c',
        activeMainNavLinkBg: '#b3d3e3',
        borderColor: '#b2d3e5',
        dropdownColor: '#C1E4F2',
        toggleColor: '#396273',
        toggleInactiveColor: '#6e7f86',
        menuSearchColor: '#396273',
        responseColor: '#b3d3e3',
        green: '#c4e3e2',
        orange: '#ddd9d1',
        red: '#d7dae8',
        textHighlightColor: '#f3f4f5',
        toolbarIconColor: '#a7ccde',
        textTemplateLabel: '#a4abb0',
        textTemplateComment: '#5c6370',
        textTemplateBlue: '#396273',
        textTemplateGreen: '#007C21',
        textTemplateBlueOpacity: '#658c9c',
        textTemplateGreenOpacity: '#4a9c64',
      },
      theme3: {
        mainPrimary: '#FFFCFE',
        mainSecondary: '#f1e3ed',
        miscPrimary: '#af88a4',
        miscSecondary: '#777',
        editorBg: '#f6ecf3',
        textContrast: '#633B58',
        lightyContrast: '#fff',
        okColor: '#ccacc3',
        attentionColor: '#ccacc3',
        warningColor: '#ccacc3',
        paramColor: '#633B58',
        categoryColor: '#633B58',
        listColor: '#e7833c',
        activeMainNavLinkBg: '#f6ecf3',
        borderColor: '#d7d9e6',
        dropdownColor: '#f6ecf3',
        toggleColor: '#633B58',
        toggleInactiveColor: '#af88a4',
        menuSearchColor: '#633B58',
        responseColor: '#e3cadc80',
        green: '#d1e5e6',
        orange: '#d5d3d9',
        red: '#d0ddf2',
        textHighlightColor: '#eabfde',
        toolbarIconColor: '#ccacc3',
        textTemplateLabel: '#a4abb0',
        textTemplateComment: '#777',
        textTemplateBlue: '#d55fde',
        textTemplateGreen: '#007C21',
        textTemplateBlueOpacity: '#E98FEF',
        textTemplateGreenOpacity: '#589f65',
      },
      theme4: {
        mainPrimary: '#dfdfdf',
        mainSecondary: '#f3f3f3',
        miscPrimary: '#5E5E5E',
        miscSecondary: '#777',
        editorBg: '#f5f5f5',
        textContrast: '#333',
        lightyContrast: '#fff',
        okColor: '#9AA4AB',
        attentionColor: '#9AA4AB',
        warningColor: '#9AA4AB',
        paramColor: '#9AA4AB',
        categoryColor: '#9AA4AB',
        listColor: '#e7833c',
        activeMainNavLinkBg: '#dfdfdf',
        borderColor: '#dfdfdf',
        dropdownColor: '#f3f3f3',
        toggleColor: '#838C91',
        toggleInactiveColor: '#bbbabb',
        menuSearchColor: '#838C91',
        responseColor: '#9AA4AB',
        green: '#a9a9a9',
        orange: '#dbb89a',
        red: '#d6a4ac',
        textHighlightColor: '#dad9d9',
        toolbarIconColor: '#9AA4AB',
        textTemplateLabel: '#a4abb0',
        textTemplateComment: '#5c6370',
        textTemplateBlue: '#61afef',
        textTemplateGreen: '#007C21',
        textTemplateBlueOpacity: '#8cc5f1',
        textTemplateGreenOpacity: '#549F61',
      },
      theme5: {
        mainPrimary: '#2c2833',
        mainSecondary: '#442a39',
        miscPrimary: '#c7b2a0',
        miscSecondary: '#c7b2a0',
        editorBg: '#4b3144',
        textContrast: '#fff0f5',
        lightyContrast: '#fff',
        okColor: '#9f486f',
        attentionColor: '#9f486f',
        warningColor: '#9f486f',
        paramColor: '#9f486f',
        categoryColor: '#9f486f',
        listColor: '#e7833c',
        activeMainNavLinkBg: '#9f486f',
        borderColor: '#9f486f',
        dropdownColor: '#4b3144',
        toggleColor: '#9f486f',
        toggleInactiveColor: '#c7b2a0',
        menuSearchColor: '#9f486f',
        responseColor: '#9f486f',
        green: '#424e57',
        orange: '#76473a',
        red: '#7c3c5a',
        textHighlightColor: '#9f486f',
        toolbarIconColor: '#9f486f',
        textTemplateLabel: '#a4abb0',
        textTemplateComment: '#5c6370',
        textTemplateBlue: '#61afef',
        textTemplateGreen: '#89ca78',
        textTemplateBlueOpacity: '#5888ba',
        textTemplateGreenOpacity: '#549F61',
      },
      theme6: {
        mainPrimary: '#F0EEE5',
        mainSecondary: '#D9D3C3',
        miscPrimary: '#414141',
        miscSecondary: '#777',
        editorBg: '#D9D3C3',
        textContrast: '#333',
        lightyContrast: '#f3f3f3',
        okColor: '#C2B8AB',
        attentionColor: '#C2B8AB',
        warningColor: '#C2B8AB',
        paramColor: '#706F6B',
        categoryColor: '#706F6B',
        listColor: '#e7833c',
        activeMainNavLinkBg: '#C2B8AB',
        borderColor: '#C2B8AB',
        dropdownColor: '#F0EEE5',
        toggleColor: '#414141',
        toggleInactiveColor: '#706F6B',
        menuSearchColor: '#706F6B',
        responseColor: '#C2B8AB',
        green: '#b2e0bf ',
        orange: '#d58b19',
        red: '#ef908f',
        textHighlightColor: '#d4cbb2',
        toolbarIconColor: '#C2B8AB',
        textTemplateLabel: '#a4abb0',
        textTemplateComment: '#5c6370',
        textTemplateBlue: '#20639B',
        textTemplateGreen: '#007C21',
        textTemplateBlueOpacity: '#61afef',
        textTemplateGreenOpacity: '#70a671',
      },
      theme7: {
        mainPrimary: '#273A4A',
        mainSecondary: '#243240',
        miscPrimary: '#839eb5',
        miscSecondary: '#74ADDB',
        editorBg: '#2D4254',
        textContrast: '#dbecfb',
        lightyContrast: '#fff',
        okColor: '#486b88',
        attentionColor: '#486b88',
        warningColor: '#486b88',
        paramColor: '#74ADDB',
        categoryColor: '#74ADDB',
        listColor: '#e7833c',
        activeMainNavLinkBg: '#243240',
        borderColor: '#243240',
        dropdownColor: '#273A4A',
        toggleColor: '#74ADDB',
        toggleInactiveColor: '#7E9696',
        menuSearchColor: '#74ADDB',
        responseColor: '#486b88',
        green: '#354d62',
        orange: '#3c4172',
        red: '#13445e',
        textHighlightColor: '#2b586f',
        toolbarIconColor: '#486b88',
        textTemplateLabel: '#a4abb0',
        textTemplateComment: '#5c6370',
        textTemplateBlue: '#61afef',
        textTemplateGreen: '#2FBE55',
        textTemplateBlueOpacity: '#74ADDB',
        textTemplateGreenOpacity: '#89ca78',
      },

      transparent: 'transparent',
      black: '#000',
      white: '#fff',
      iconColor: '#f3f3f3',
      green: '#89ca78',
      orange: '#ff9b46',
      red: '#ef596f',
      gray: '#595959',
    },
    spacing: {
      px: '1px',
      0: '0',
      5: '5px',
      10: '10px',
      15: '15px',
      20: '20px',
      25: '25px',
      30: '30px',
      35: '35px',
      40: '40px',
      45: '45px',
      50: '50px',
      55: '55px',
      60: '60px',
      65: '65px',
      70: '70px',
      75: '75px',
      80: '80px',
      85: '85px',
      90: '90px',
      95: '95px',
      100: '100px',
    },
    screens: {
      xs: { max: '500px' },
      sm: { max: '768px' },
      md: { max: '1024px' },
      lg: { max: '1366px' },
      xl: { max: '1920px' },
    },
    fontSize: {
      base: '12px',
      10: '10px',
      11: '11px',
      12: '12px',
      13: '13px',
      14: '14px',
      15: '15px',
      16: '16px',
      17: '17px',
      18: '18px',
      19: '19px',
      20: '20px',
      21: '21px',
      22: '22px',
      23: '23px',
      24: '24px',
      '2xs': '.7em',
      xs: '.75em',
      sm: '.875em',
      md: '1.125em',
      lg: '1.25em',
      xl: '1.5em',
      '2xl': '2.25em',
      '3xl': '3em',
    },
    textColor: (theme) => theme('colors'),
    background: (theme) => theme('colors'),
    backgroundPosition: {
      bottom: 'bottom',
      center: 'center',
      left: 'left',
      'left-bottom': 'left bottom',
      'left-top': 'left top',
      right: 'right',
      'right-bottom': 'right bottom',
      'right-top': 'right top',
      top: 'top',
    },
    backgroundSize: {
      auto: 'auto',
      cover: 'cover',
      contain: 'contain',
    },
    borderWidth: {
      default: '1px',
      0: '0',
      2: '2px',
      3: '3px',
      4: '4px',
      5: '5px',
      6: '6px',
      7: '7px',
      8: '8px',
      9: '9px',
      10: '10px',
    },
    borderColor: (theme) => ({
      ...theme('colors'),
      default: theme('colors.black', 'currentColor'),
    }),
    borderRadius: {
      none: '0',
      xs: '3px',
      sm: '5px',
      md: '7px',
      lg: '10px',
      xl: '20px',
      full: '50%',
    },
    cursor: {
      auto: 'auto',
      default: 'default',
      pointer: 'pointer',
      wait: 'wait',
      move: 'move',
      'not-allowed': 'not-allowed',
    },
    width: (theme) => ({
      auto: 'auto',
      ...theme('spacing'),
      '1/2': '50%',
      '1/3': '33.33333%',
      '2/3': '66.66667%',
      '1/4': '25%',
      '3/4': '75%',
      '1/5': '20%',
      '2/5': '40%',
      '3/5': '60%',
      '4/5': '80%',
      '1/6': '16.66667%',
      '5/6': '83.33333%',
      full: '100%',
      screen: '100vw',
    }),
    height: (theme) => ({
      auto: 'auto',
      ...theme('spacing'),
      full: '100%',
      screen: '100vh',
    }),
    minWidth: {
      0: '0',
      '1/2': '50%',
      '1/3': '33.33333%',
      '2/3': '66.66667%',
      '1/4': '25%',
      '3/4': '75%',
      '1/5': '20%',
      '2/5': '40%',
      '3/5': '60%',
      '4/5': '80%',
      '1/6': '16.66667%',
      '5/6': '83.33333%',
      full: '100%',
    },
    minHeight: {
      0: '0',
      full: '100%',
      screen: '100vh',
    },
    maxWidth: {
      '1/2': '50%',
      '1/3': '33.33333%',
      '2/3': '66.66667%',
      '1/4': '25%',
      '3/4': '75%',
      '1/5': '20%',
      '2/5': '40%',
      '3/5': '60%',
      '4/5': '80%',
      '1/6': '16.66667%',
      '5/6': '83.33333%',
      full: '100%',
      none: 'none',
    },
    maxHeight: {
      full: '100%',
      screen: '100vh',
      none: 'none',
    },
    padding: (theme) => theme('spacing'),
    margin: (theme) => ({ auto: 'auto', ...theme('spacing') }),
    negativeMargin: (theme) => theme('spacing'),
    objectPosition: {
      bottom: 'bottom',
      center: 'center',
      left: 'left',
      'left-bottom': 'left bottom',
      'left-top': 'left top',
      right: 'right',
      'right-bottom': 'right bottom',
      'right-top': 'right top',
      top: 'top',
    },
    boxShadow: {
      default: '0 1px 3px 0 rgba(0, 0, 0, .1), 0 1px 2px 0 rgba(0, 0, 0, .06)',
      md: '0 4px 6px -1px rgba(0, 0, 0, .1), 0 2px 4px -1px rgba(0, 0, 0, .06)',
      lg: '0 10px 15px -3px rgba(0, 0, 0, .1), 0 4px 6px -2px rgba(0, 0, 0, .05)',
      xl: '0 20px 25px -5px rgba(0, 0, 0, .1), 0 10px 10px -5px rgba(0, 0, 0, .04)',
      '2xl': '0 25px 50px -12px rgba(0, 0, 0, .25)',
      inner: 'inset 0 2px 4px 0 rgba(0,0,0,0.06)',
      outline: '0 0 0 3px rgba(66,153,225,0.5)',
      none: 'none',
    },
    zIndex: {
      auto: 'auto',
      0: 0,
      5: 5,
      10: 10,
      15: 15,
      20: 20,
      25: 25,
      30: 30,
      35: 35,
      40: 40,
      45: 45,
      50: 50,
    },
    opacity: {
      0: '0',
      25: '.25',
      50: '.5',
      75: '.75',
      100: '1',
    },
    fill: {
      current: 'currentColor',
    },
    stroke: {
      current: 'currentColor',
    },
    flex: {
      1: '1 1 0%',
      auto: '1 1 auto',
      initial: '0 1 auto',
      none: 'none',
    },
    flexGrow: {
      0: 0,
      default: 1,
    },
    flexShrink: {
      0: 0,
      default: 1,
    },
    listStyleType: {
      none: 'none',
      disc: 'disc',
      decimal: 'decimal',
    },
    inset: {
      0: 0,
      auto: 'auto',
    },
    container: {},
  },
  variants: {
    appearance: ['responsive'],
    backgroundAttachment: ['responsive'],
    backgroundColor: ['responsive', 'hover', 'focus'],
    backgroundPosition: ['responsive'],
    backgroundRepeat: ['responsive'],
    backgroundSize: ['responsive'],
    borderCollapse: [],
    borderColor: ['responsive', 'hover', 'focus'],
    borderRadius: ['responsive'],
    borderStyle: ['responsive'],
    borderWidth: ['responsive'],
    cursor: ['responsive'],
    display: ['responsive'],
    flexDirection: ['responsive'],
    flexWrap: ['responsive'],
    alignItems: ['responsive'],
    alignSelf: ['responsive'],
    justifyContent: ['responsive'],
    alignContent: ['responsive'],
    flex: ['responsive'],
    flexGrow: ['responsive'],
    flexShrink: ['responsive'],
    float: ['responsive'],
    fontFamily: ['responsive'],
    fontWeight: ['responsive', 'hover', 'focus'],
    height: ['responsive'],
    lineHeight: ['responsive'],
    listStylePosition: ['responsive'],
    listStyleType: ['responsive'],
    margin: ['responsive'],
    maxHeight: ['responsive'],
    maxWidth: ['responsive'],
    minHeight: ['responsive'],
    minWidth: ['responsive'],
    negativeMargin: ['responsive'],
    objectFit: ['responsive'],
    objectPosition: ['responsive'],
    opacity: ['responsive'],
    outline: ['focus'],
    overflow: ['responsive'],
    padding: ['responsive'],
    pointerEvents: ['responsive'],
    position: ['responsive'],
    inset: ['responsive'],
    resize: ['responsive'],
    boxShadow: ['responsive', 'hover', 'focus'],
    fill: [],
    stroke: [],
    tableLayout: ['responsive'],
    textAlign: ['responsive'],
    textColor: ['responsive', 'hover', 'focus'],
    fontSize: ['responsive'],
    fontStyle: ['responsive'],
    textTransform: ['responsive'],
    textDecoration: ['responsive', 'hover', 'focus'],
    fontSmoothing: ['responsive'],
    letterSpacing: ['responsive'],
    userSelect: ['responsive'],
    verticalAlign: ['responsive'],
    visibility: ['responsive'],
    whitespace: ['responsive'],
    wordBreak: ['responsive'],
    width: ['responsive'],
    zIndex: ['responsive'],
  },
  corePlugins: {},
  plugins: [],
}
